logging.config: classpath:log4j2.xml

## Dubbo \u670D\u52A1\u63D0\u4F9B\u8005\u914D\u7F6E
spring.dubbo:
  application:
    name: springboot-dubbo-mybatis
    owner: jiayongming
    organization: jinhui365.com
    logger: slf4j

  registry:
    address: zookeeper://zookeeper:2181
    file: /data/dubbo/springboot-dubbo-mybatis/dubbo-registry.properties

  protocol:
    name: dubbo
    port: 30086

  monitor.protocol: registry

  provider:
    cluster: failfast
    timeout: 2147483647

  consumer:
    layer: biz
    check: false
    cluster: failfast
    timeout: 2147483647
    owner: jiayongming

  basePackage: com.ymjia.demo.application.service.impl

# jdbc-DruidDataSource\u8FDE\u63A5\u6C60\u914D\u7F6E
application.datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.0.0.20:3307/channels?defaultBatchValue=1000&amp;useUnicode=true&amp;characterEncoding=utf8mb4&amp;useSSL=false&amp;autoReconnect=true
  username: analyse
  password: GemanticYes!
  connection-timeout: 20000
  testWhileIdle: true
  validationQuery: SELECT 1
  timeBetweenEvictionRunsMillis: 300000
  initialSize: 10
  minIdle: 5
  maxActive: 20
  maxWait: 60000
  minEvictableIdleTimeMillis: 300000
  testOnBorrow: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true