# jdbc-DruidDataSource\u8FDE\u63A5\u6C60\u914D\u7F6E
application.datasource:
  url: jdbc:mysql://db.wealth.channel:3306/channels?defaultBatchValue=1000&amp;useUnicode=true&amp;characterEncoding=utf8mb4&amp;useSSL=false&amp;autoReconnect=true
  username: channels
  password: vEk1TXLqXHzkYdR4h7Yr5X9YB4EZC46q